### ISSUE TITLE
[FEATURE] Documentation about permissions required to connect

### ISSUE THREAD

**Issue by bartleboeuf** [geek-fun/dockit#119]
**Is your feature request related to a problem? Please describe.**
It would be necessary to provide a list of the minimum permissions and Opensearch roles required for a user to connect via the client Dockit. Today, it's difficult to find the right permissions for a non-administrator user to be able to connect.

**Additional context**
At present, we have internal users who should only be able to manipulate their indexes and documents in the domain. They do not have access to administration functions.

**Comment by Blankll** [comment]
Hi @bartleboeuf , thanks for reporting, that helps a lot to DocKit,
as mentioned, there are two improvements we will make:
- document the permission requirement for the user.
- a clear & nicer notification when the user's action hits the permission issue 

feel free to comment if you have more thoughts on it, we will be looking into it and implement it asap.

**Comment by Blankll** [comment]
Hi there, we have added an error message dialog when the user meet any permission issues, and the minimum required permission as `view_index_metadata` has been documented in the official site, whats more, we have enabled the ability to specify the index/alias name when to connect to a server, feel free to download the latest version 0.4.8 and try it out

**Comment by bartleboeuf** [comment]
It works fine 👍 Thanks for this quick improvement.
