### ISSUE TITLE
[BUG] Ability to query ES/OS system indexes

### ISSUE THREAD

**Issue by DwaneHall** [geek-fun/dockit#120]
**Describe the bug**
Enable the ability query system indexes. (They appear to be treated as invalid queries)

i.e. GET .opendistro_security/_search
*notice the leading "." appears to cause validation issues
 
**Reproduce Steps**
1. Attempt to query any system index (prefixed by a leading ".")

**Expected behavior**
Queries to these indexes are recognised as a valid format and able to be submitted using the (excellent!) tool

**Comment by Blankll** [comment]
thanks for report, we will fix it soon

**Comment by Blankll** [comment]
Hi there, it has been fixed in the latest version 0.4.8, feel free to try it out, any other bugs/issues, raise issues  if there still any other problems

**Comment by DwaneHall** [comment]
Thanks for the quick fix! Working as expected
