### ISSUE TITLE
Question - External file storage?

### ISSUE THREAD

**Issue by DwaneHall** [geek-fun/dockit#121]
Hey guys, awesome project btw.  It looks like there's active development going on with an aim at v1 being the stable baseline.  On the UI it appears some features are functional (i.e "Manage"), and others placeholders for future work (i.e. "History").  I'm playing behind a corporate proxy so it's difficult to know if things have not been implemented yet, or if my local env is the issue.  For us saving and using external storage for our files/scripts is a showstopper but every time I try to save over the example scripts in the UI it's not saved. Has the external file (i.e. "Files" menu item) been fully implemented yet or should I return for a better view of the tool when v1 is released?

**Comment by Blankll** [comment]
Hi @DwaneHall thanks for giving us your real user experience, which is valuable for us,  yes, we are actively implementing functions for V1 as the first comprehensive stable version.
From your description, I reckon there are two features that you highly use in your workflow:
- save/load queries from external storage
  > DocKit is currently only able to save single file and it was loaded when you open DocKit(ctlOrCmd + S), we have a ticket for it before but have not seen any request from a user, so we closed it as not a priority, nice to hear your voice and we are going to open it again and place into v1 roadmap.
- support customize proxy and DocKit send a request through the configured proxy
  > DocKit currently does not support customized proxy, and so farDocKIt only sent HTTP requests to the connected ES server, so it follows the host system's configuration. We will tag it as a feature request, but the external storage will be the first priority.

let me know if I miss anything and feel free to raise anything about DocKit, thanks

**Comment by DwaneHall** [comment]
Thanks @Blankll!
It would be great to support the ability to organise your different scripts into files/folders etc under the "Files" menu option and use them against your choice of connection.  Typically we have multiple Open Search/ES/Solr environments (DEV/SIT/UAT/PROD etc,) and the scripts/queries want to run against each environment can be different.  That way you could organise your scripts/save them to some external file location and file hierarchy.  The combination of your active selected connection and open script/file would dictate the environment your query is executed against.

Re saving my scripts I did find it a bit hit and miss with multiple connections in the current state. I created 4+ Open Search connections and saved multiple times and noticed scripts being overridden or default back to the baseline example scripts (I initially thought each connection used a new script file so your response clarified this is not the case).  Enhanced file management capability mentioned above would definitely make this a cleaner experience.  Tools like Open Search have the "Dev Tools" feature that uses local storage in the browser and I've been caught out with browser cache clears that wipe my scripts that had got out of sink with persisted local copies.   In my opinion reliable file management (autosaves etc.) would be a huge win for adoption of the tool.

My comment re proxy may come in handy for some users but is not a show stopper for us atm as (looks like you have it already in the OpenAI configuration). My comment on this matter was more related to my difficulty testing as I was not sure if it was our corporate firewall causing some features not to work, or if one of the roadmap features had not been implemented yet.  This is not related to the tool more our specific environment.

Thanks again for the effort that's gone into the tool so far it really shows great potential!

**Comment by Blankll** [comment]
Hi @DwaneHall , Files/Folder has been enabled in the latest version 0.4.9, feel free to try it out 🚀 

I will close this issue, any feedback/bugs feel free to raise another issue and we appreciate it!

**Comment by DwaneHall** [comment]
Hey @Blankll I had a quick play with the new file feature. Quick one what are the supported file types?  I've been unable to open any file that i've tried to save though the ui (it creates ok, but Dockit returns a "Dockit does not support this filetype" message when opening). I've tried no file extension, .txt, .json.

Thanks

**Comment by Blankll** [comment]
hi， dockit use file as .search， try to use it， and I might need add a user friendly message to indicate that， thanks！
