### ISSUE TITLE
[feature] Keyboard shortcuts

### ISSUE THREAD

**Issue by tomsquest** [geek-fun/dockit#36]
Hi,

Playing with Dockit. 
The UI is pretty neat! 
I found it really useful to get a bunch of connections and being able to switch between them.
:+1: :star: 

Do you plan to implement keyboard shortcuts?

There are the one of Kibana, like ctrl+enter that fire the underline request, which should be very common for instance.

![image](https://github.com/geek-fun/dockit/assets/365778/f50ed847-5722-481e-afb0-ccd06673484f)

**Comment by Blankll** [comment]
thanks for your feedback, yes definitely, I will definitely add it, I just wanna post DocKit to the end user as soon as possible to get enough feedback to improve it from the real user requirement, this is the good case then, I will work on it

**Comment by Blankll** [comment]
| Feature         | Shortcut                | Description                                                  | State              |
| --------------- | ----------------------- | ------------------------------------------------------------ | ------------------ |
| General editing | `Ctrl/Cmd + I`          | Auto indent current request.                                 |                    |
| General editing | `Ctrl + Space`          | Open Autocomplete (even if not typing).                      |                    |
| General editing | `Ctrl/Cmd + Enter`      | Submit request.                                              |                    |
| General editing | `Ctrl/Cmd + Up/Down`    | Jump to the previous/next request start or end.              |                    |
| General editing | `Ctrl/Cmd + Alt + L`    | Collapse/expand current scope.                               |                    |
| General editing | `Ctrl/Cmd + Option + 0` | Collapse all scopes but the current one. Expand by adding a shift. |                    |
| Autocomplete    | `Down arrow`            | Switch focus to autocomplete menu. Use arrows to further select a term. | :white_check_mark: |
| Autocomplete    | `Enter/Tab`             | Select the currently selected or the top most term in autocomplete menu. | :white_check_mark: |
| Autocomplete    | `Esc`                   | Close autocomplete menu.                                     | :white_check_mark: |

**Comment by Blankll** [comment]
the base shortcuts listed above has been added to the latest version, can download and have a try, I will close this issue, well comes to raise issues if you find any other stuffs not working as expected or features you want 😄

**Comment by tomsquest** [comment]
Excellent !
