### ISSUE TITLE
feature: relaxed json support (json5)

### ISSUE THREAD

**Issue by tomsquest** [geek-fun/dockit#42]
Hi,

In Kibana Devtools, it is very annoying to "fix" you data to be json, adding double quotes and comma, but not too much comma else there is a syntax error.

![image](https://github.com/geek-fun/dockit/assets/365778/10769245-0cc5-42e8-a566-c168b9a293e4)

This feature idea is to use a relaxed json option, for example, using json5 in the editor and converting the json5 to json before sending to Elastic. This would allow a syntax that is way more fast to type, and so convenient.

Today, DocKit seems to run the relaxed json (without syntax highlighting), but the result fails ES side.

![image](https://github.com/geek-fun/dockit/assets/365778/aa11aa75-63ca-43e4-a98d-152ecc0933dc)

**Comment by Blankll** [comment]
Hi there, it's been a while but JSON5 has finally been enabled,  big welcome for people to explore, 
I'm going close this issue, but feel free to raise another if any bug/improvement there
