### ISSUE TITLE
bug: An error occurs when the content of the API response is in non-standard JSON format.

### ISSUE THREAD

**Issue by drlifeL** [geek-fun/dockit#56]
Description
An error occurs when the content of the API response is in non-standard JSON format.
eg: ES `_cat` API

Steps To Reproduce
1.Open dockit
2.creare ES connection
3.access _cat API

Environment
Elasticsearch version: 6.8.3
Operating system: MacOS 14.1.1
dockit version: 0.3.0
How are you running dockit ：DocKit-0.3.0-universal.dmg

**Comment by Blankll** [comment]
thanks @drlifeL for the report, Ive reproduce the issue, will fix it in the next version,

**Comment by Blankll** [comment]
new version has released, feel free to check, close this issue
